name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.4.0
  - pyarrow=2.0
  - pip:
      - wandb==0.10.21